# Generated by Django 5.0.4 on 2024-04-20 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='data_entrega',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monografia',
            name='palavras_chave',
            field=models.CharField(default='America/Sao_Paulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monografia',
            name='resumo',
            field=models.TextField(default='America/Sao_Paulo'),
            preserve_default=False,
        ),
    ]
