# Generated by Django 5.0.4 on 2024-04-24 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texto', '0002_monografia_data_entrega_monografia_palavras_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
