# Generated by Django 5.0.4 on 2024-04-24 00:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('texto', '0003_monografia_arquivo_alter_monografia_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='area_concentração',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='áreas pesquisa'),
        ),
        migrations.AddField(
            model_name='monografia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor_monografias', to='equipe.pesquisador'),
        ),
        migrations.AddField(
            model_name='monografia',
            name='coorientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador_monografias', to='equipe.pesquisador'),
        ),
        migrations.AddField(
            model_name='monografia',
            name='nota_final',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='nota final'),
        ),
        migrations.AddField(
            model_name='monografia',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='uploads'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='data_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='palavras_chave',
            field=models.CharField(max_length=255, verbose_name='palavras chaves'),
        ),
    ]
