# Generated by Django 5.0.4 on 2024-04-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('texto', '0005_monografia_banca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(default='1', upload_to='uploads/', verbose_name='uploads'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='autor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='autor_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='coorientador',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='coorientador_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='orientador',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='orientador_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='palavras_chave',
            field=models.CharField(default='1', max_length=255, verbose_name='palavras chaves'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='resumo',
            field=models.TextField(default='1', verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='titulo',
            field=models.CharField(default='1', max_length=255, verbose_name='titulo'),
        ),
    ]
