# Generated by Django 5.0.4 on 2024-04-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('texto', '0007_alter_monografia_arquivo_alter_monografia_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(upload_to='', verbose_name='uploads'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='banca',
            field=models.ManyToManyField(blank=True, null=True, to='equipe.pesquisador', verbose_name='banca'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='orientador',
            field=models.ForeignKey(limit_choices_to={'cargo': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_monografias', to='equipe.pesquisador'),
        ),
    ]
