# Generated by Django 5.0.4 on 2024-04-24 23:51

import django.core.validators
import django.db.models.deletion
import texto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('texto', '0008_alter_monografia_arquivo_alter_monografia_banca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(help_text="Suba somente PDF's ou Docx's", upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), texto.models.validar_extensao_texto], verbose_name='uploads'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='banca',
            field=models.ManyToManyField(blank=True, limit_choices_to={'cargo': 'PROFESSOR'}, null=True, to='equipe.pesquisador', verbose_name='banca'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='coorientador',
            field=models.ForeignKey(limit_choices_to={'cargo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='coorientador_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='orientador',
            field=models.ForeignKey(limit_choices_to={'cargo': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='orientador_monografias', to='equipe.pesquisador'),
        ),
    ]
