# Generated by Django 5.0.4 on 2024-04-25 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texto', '0009_alter_monografia_arquivo_alter_monografia_banca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='nota_final',
            field=models.FloatField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100)], verbose_name='nota final'),
        ),
    ]
