# Generated by Django 5.0.4 on 2024-05-13 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
        ('texto', '0011_alter_monografia_autor_alter_monografia_banca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='autor',
            field=models.OneToOneField(limit_choices_to={'cargo': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='autor_monografias', to='equipe.pesquisador'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='banca',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('cargo', 'PROFESSOR'), ('cargo', 'TECNICO'), _connector='OR'), null=True, to='equipe.pesquisador', verbose_name='banca'),
        ),
    ]
